# Generated by Django 5.0.3 on 2024-03-29 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('message_role', models.TextField()),
                ('pipeline_id', models.CharField(max_length=255)),
                ('session_id', models.UUIDField()),
            ],
            options={
                'db_table': 'message_history',
            },
        ),
    ]
